# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "F. Leah Nez"                                # Your name
  description: "PhD Student in Bioethics"   # A brief slogan (optional)
  image: img/0317__2025-05-30DineSummit.jpg
  
  favicon: img/favicon_fln.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo_fln.png
    
    # your sub-pages
    left:
      - text: "Education and Training"
        href: education/index.qmd
      - text: "Professional Experience"
        href: experiences/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: instagram
        href: https://www.instagram.com/existential_crisis3/
      - icon: linkedin
        href: https://www.linkedin.com/in/nezfl/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.fln3@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - darkly
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true